// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EksamenSem2.Models;

[Table("Kompetence")]
public partial class Kompetence
{
    [Key]
    [Column("Kompetence_ID")]
    public int KompetenceId { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Navn { get; set; }

    [Column("Kompetence")]
    [StringLength(255)]
    [Unicode(false)]
    public string Kompetence1 { get; set; }

    [ForeignKey("KompetenceId")]
    [InverseProperty("Kompetences")]
    public virtual ICollection<Medarbejder> Medarbejders { get; set; } = new List<Medarbejder>();
}