// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EksamenSem2.Models;

[PrimaryKey("MedarbejderId", "KompetenceId")]
[Table("MedarbejderKompetence")]
public partial class MedarbejderKompetence
{
    [Key]
    [Column("Kompetence_ID")]
    public int KompetenceId { get; set; }

    [Key]
    [Column("Medarbejder_ID")]
    public int MedarbejderId { get; set; }

    [ForeignKey("KompetenceId")]
    [InverseProperty("MedarbejderKompetences")]
    public virtual Kompetence Kompetence { get; set; }

    [ForeignKey("MedarbejderId")]
    [InverseProperty("MedarbejderKompetences")]
    public virtual Medarbejder Medarbejder { get; set; }
}