// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EksamenSem2.Models;

[Table("Medarbejder")]
public partial class Medarbejder
{
    [Key]
    public int Id { get; set; }

    public double? Løn { get; set; }

    public double? Timeløn { get; set; }

    public string Beskrivelse { get; set; }

    public int? RolleId { get; set; }

    [StringLength(255)]
    public string Navn { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Email { get; set; }

    public int? TlfNr { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Password { get; set; }

    [InverseProperty("Medarbejder")]
    public virtual ICollection<MedarbejderKompetence> MedarbejderKompetences { get; set; } = new List<MedarbejderKompetence>();

    [ForeignKey("RolleId")]
    [InverseProperty("Medarbejders")]
    public virtual Rolle Rolle { get; set; }

    [InverseProperty("Medarbejder")]
    public virtual ICollection<VagtPlan> VagtPlans { get; set; } = new List<VagtPlan>();
}