// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EksamenSem2.Models;

[Table("Medarbejder")]
public partial class Medarbejder
{
    [Key]
    public int Id { get; set; }

    public double? Løn { get; set; }

    public double? Timeløn { get; set; }

    public string Beskrivelse { get; set; }

    public int? RolleId { get; set; }

    [StringLength(255)]
    [RegularExpression("^[a-zA-Z\\s]+$", ErrorMessage = "Kun bogstaver er tilladt")]
    public string Navn { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    [Required]
    [RegularExpression(@"^[^@\s]+@[^@\s]+.[^@\s]+$", ErrorMessage = "Indtast en gyldig emailadresse.")]
    public string Email { get; set; }

    [Range(10000000, 99999999, ErrorMessage ="Dit telefon nummer skal være 8 cifre")]
    public int? TlfNr { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    [Required]
    [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,}$", ErrorMessage = "Passwordet skal indeholde både store og små bogstaver samt tal, og være mindst 8 tegn langt.")]
    public string Password { get; set; }

    [InverseProperty("Medarbejder")]
    public virtual ICollection<MedarbejderKompetence> MedarbejderKompetences { get; set; } = new List<MedarbejderKompetence>();

    [ForeignKey("RolleId")]
    [InverseProperty("Medarbejders")]
    public virtual Rolle Rolle { get; set; }

    [InverseProperty("Medarbejder")]
    public virtual ICollection<VagtPlan> VagtPlans { get; set; } = new List<VagtPlan>();
}